name: GenMap
version: 0.1
description: Generates a map
author: zifnab06


main: net.zifnab06.GenMap.GenMap
database: false

commands:
  generate:
    description: Generate Map.
    permission: genmap.genmap
    usage: /generate world radius (3000 = 6000x6000 square world)
  generate-status:
    description: Shows status
    premisssion: genmap.genmap
    usage: /generate-status
permissions:
  genmap.genmap:
    description: Allows map generation.
    default: op
