name: GenMap
version: 0.1
description: Generates a map
author: zifnab06


main: net.zifnab06.Genmap.GenMap
database: false

commands:
  generate:
    description: Generate Map.
    permission: genmap.genmap
    usage: /generate world radius (3000 = 6000x6000 square world)
permissions:
  genmap.genmap:
    description: Allows map generation.
    default: op